
//CLOUDINARY
export const REACT_APP_CLOUDINARY_CLOUD_NAME = process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const REACT_APP_CLOUDINARY_UPLOAD_PRESET = process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;

//EMAILJS
export const REACT_APP_EMAILJS_SERVICEID = process.env.REACT_APP_EMAILJS_SERVICEID;
export const REACT_APP_EMAILJS_TEMPLATEID = process.env.REACT_APP_EMAILJS_TEMPLATEID;
export const REACT_APP_EMAILJS_USER_ID = process.env.REACT_APP_EMAILJS_USER_ID;

//EMAILJS TEST
export const REACT_APP_EMAILJS_SERVICEID_TEST = process.env.REACT_APP_EMAILJS_SERVICEID_TEST;
export const REACT_APP_EMAILJS_TEMPLATEID_TEST = process.env.REACT_APP_EMAILJS_TEMPLATEID_TEST;

// RESEND
export const REACT_APP_RESEND_API_KEY = process.env.REACT_APP_RESEND_API_KEY;
