//CLOUDINARY
export const REACT_APP_CLOUDINARY_CLOUD_NAME = import.meta
  .envREACT_APP_CLOUDINARY_CLOUD_NAME;
export const REACT_APP_CLOUDINARY_UPLOAD_PRESET = import.meta
  .envREACT_APP_CLOUDINARY_UPLOAD_PRESET;

//EMAILJS
export const REACT_APP_EMAILJS_SERVICEID = import.meta
  .envREACT_APP_EMAILJS_SERVICEID;
export const REACT_APP_EMAILJS_TEMPLATEID = import.meta
  .envREACT_APP_EMAILJS_TEMPLATEID;
export const REACT_APP_EMAILJS_USER_ID = import.meta
  .envREACT_APP_EMAILJS_USER_ID;

//EMAILJS TEST
export const REACT_APP_EMAILJS_SERVICEID_TEST = import.meta
  .envREACT_APP_EMAILJS_SERVICEID_TEST;
export const REACT_APP_EMAILJS_TEMPLATEID_TEST = import.meta
  .envREACT_APP_EMAILJS_TEMPLATEID_TEST;

// RESEND
export const REACT_APP_RESEND_API_KEY = import.meta.envREACT_APP_RESEND_API_KEY;

//GOOGLE ANALYTICS
export const REACT_APP_TRACKING_ID = import.meta.envREACT_APP_TRACKING_ID;
