
//CLOUDINARY
export const REACT_APP_CLOUDINARY_CLOUD_NAME = process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const REACT_APP_CLOUDINARY_UPLOAD_PRESET = process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;

//EMAILJS
export const REACT_APP_EMAILJS_SERVICEID = process.env.REACT_APP_EMAILJS_SERVICEID;
export const REACT_APP_EMAILJS_TEMPLATEID = process.env.REACT_APP_EMAILJS_TEMPLATEID;
export const REACT_APP_EMAILJS_USER_ID = process.env.REACT_APP_EMAILJS_USER_ID;
